# use docker image to persist phpstorm ide settings across new workspace or reboot 
#   Simply use `tmy-persist-ide-settings-through-image-for-gitpod` (should be in image already), then get the 
#   latest tag name, update below
#   NOTE: in theory should not need the tag name, but seems gitpod is caching image locally, hence to use 
#   tag name to ensure latest image is pulled
image: tmy2017/gitpod-pstorm-with-php71-mysql8:ver-1649599399

tasks:
  # USAGE NOTE on PHPSTORMS in gitpod: 
  #   Using docker image to persist IDE settings has imitation of 
  #   !!! MIGHT need to git check in workspace.xml (ex: for xdebug ide listening port) due to some settings 
  #     are not able to "share through VCS". Similar issue: https://youtrack.jetbrains.com/issue/WI-57046
  #     although it is not recommended by official guideline: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems
  # use projector run.sh to directly invoke project directory. Thanks to 
  #   https://github.com/shaal/DrupalPod/blob/main/.gitpod/utils/phpstorm.template.sh
  #   now uses custom global command to make config cleaner here
  - command: tmy-pstorm-launch-GITPOD_REPO_ROOT
  # NOTE: below `sudo chmod o+rwx .` - this dot specific "here" directory is different from wildcard in line below!
  - init: | 
      make deps
      docker-compose build
      docker-compose pull
      sudo chmod o+rwx . 
      sudo chmod -R o+rw *
    command: |
      docker-compose up 
# split right so normal terminal can be seen 
    openMode: split-right
# direct open preview   
ports:
  # open browser could be blocked by browser
  - port: 19999
    onOpen: open-browser
  - port: 1000-9000
    onOpen: ignore
# still applied even above implicitly says ignore! 
# NOTE: can not have more than two using onOpen: open-preview
  - port: 8041
    visibility: private
    onOpen: open-preview
vscode:
  extensions:
    - https://github.com/jimmygc/linenote-codelens/releases/download/1.0.1/linenote-codelens-1.0.1.vsix
    - bmewburn.vscode-intelephense-client
    - tabnine.tabnine-vscode
    # - eamodio.gitlens
    - ms-azuretools.vscode-docker
    - felixfbecker.php-debug
    - alexcvzz.vscode-sqlite
    - humao.rest-client
    - pkief.material-icon-theme
    # - alefragnani.bookmarks
    - ms-vscode.live-server

github:
  prebuilds:
    master: true
    branches: true