PUT http://localhost:8030/courses/395dfc17-74c1-409e-b918-318395a09641
Content-Type: application/x-www-form-urlencoded

id=99&name=azfazef&duration=hihihihi

###
GET http://localhost:8030/metrics
###
GET http://localhost:8030/health-check
